I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_minimap.rpy", line 8, in script call
    call shoppingmall
  File "game/script_shoppingmall.rpy", line 64, in script
    scene bg shoppingmall_1 a with fade
Exception: Image 'bg shoppingmall_1' does not accept attributes 'a'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_minimap.rpy", line 8, in script call
    call shoppingmall
  File "game/script_shoppingmall.rpy", line 64, in script
    scene bg shoppingmall_1 a with fade
  File "renpy/ast.py", line 1328, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/core.py", line 390, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'bg shoppingmall_1' does not accept attributes 'a'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
MBTI 프로젝트 
Mon Dec 20 13:25:00 2021
